### ISSUE TITLE
Error running kernel because startup code overlaps with built in BIOS code

### ISSUE THREAD

**Issue by OscarShiang** [DavidSpickett/ARMMultiTasking#1]
Hello, 

I just have encounter some problems while compiling this repository.

Here is the tool chain I used and the version of them
```shell
$ cat /etc/os-release | head -6
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

$ aarch64-elf-gcc --version | head -1
aarch64-elf-gcc (Linaro GCC 7.5-2019.12) 7.5.0

$ qemu-system-arm --version | head -1
QEMU emulator version 5.1.0
```

`aarcdh64-elf-gcc` is from [Linaro Releases](https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-elf/)
`qemu 5.1` is from [Download QEMU - QEMU](https://www.qemu.org/download/#source)

And this is the error message when  I execute `make` command

```shell
$ make

(skip)

[  9%] Building C object CMakeFiles/fibres.dir/src/user/timer.c.o
[  9%] Building C object CMakeFiles/fibres.dir/src/user/fibre.c.o
[  9%] Building C object CMakeFiles/fibres.dir/src/hw/arm_common/gic.c.o
[  9%] Linking C executable fibres
aarch64-elf-gcc (Linaro GCC 7.5-2019.12) 7.5.0
[  9%] Built target fibres
Scanning dependencies of target test_fibres
make[2]: *** [CMakeFiles/test_fibres.dir/build.make:57: test_fibres] Error 1
make[1]: *** [CMakeFiles/Makefile2:321: CMakeFiles/test_fibres.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I try to execute the command in `CMakeFiles/test_fibres.dir/build.make:57`, and I got this error:

```shell
$ qemu-system-aarch64 -M virt -cpu cortex-a57 -m 1M -nographic -semihosting -kernel fibres -serial file:fibres_got.log
QEMU 5.1 monitor - type 'help' for more information
(qemu) rom: requested regions overlap (rom dtb. free=0x0000000000007d30, addr=0x0000000000000000)
qemu-system-aarch64: rom check and register reset failed
```

**Comment by DavidSpickett** [comment]
Hi, thanks for the great report!

I was able to reproduce locally and I think the issue is that we're placing the startup code in space reserved for the boot ROM. This was likely allowed in earlier QEMU versions but tightened up later. (see the comment on base_memmap: https://git.qemu.org/?p=qemu.git;a=blob;f=hw/arm/virt.c)

```
$ aarch64-elf-objdump -h fibres

fibres:     file format elf64-littleaarch64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .startup      00000da0  0000000000000000  0000000000000000  00000800  2**11
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .text         0000baac  0000000000000dc0  0000000000000dc0  000015c0  2**6
                  CONTENTS, ALLOC, LOAD, CODE
  2 .rodata       00000fa0  000000000000c870  000000000000c870  0000d070  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .rodata.str1.8 00000188  000000000000d810  000000000000d810  0000e010  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
<...>
```

For reference the versions being used in CI and my local development are:
```
aarch64-elf-gcc (Linaro GCC 7.4-2019.02) 7.4.1 20181213
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.32)
```

So, the workaround:
You can ignore the compiler version but try an older QEMU. I think 2.11.1 is 18.04's default, I suggest you checkout the QEMU source and build from the git tag for that version. (configure with `--target-list=aarch64-softmmu` to save some build time)

The actual fix:
Would be to build the startup/interrupt vectors as their own binary and do
```
qemu-system-aarch64 <...> -bios boot.bin -kernel fibres
```
That requires some CMake surgery of course.

**Comment by DavidSpickett** [comment]
Did some digging on this:
* You can put the startup code in its own boot binary and load it with `-binary` but then that code must also load the kernel. Which I do not know how to do at this point. (currently QEMU sets us up to start the kernel directly, that process must have got more strict in the newer versions)
* You can move all the code into RAM, which works fine for AArch64 but not for Armv7 because on Armv7 we aren't as free to relocate the exception vectors.

Also, Thumb seems to work fine with the latest QEMU. So there's another workaround for you.

**Comment by jserv** [comment]
> The actual fix:
> Would be to build the startup/interrupt vectors as their own binary and do
> ```
> qemu-system-aarch64 <...> -bios boot.bin -kernel fibres
> ```

Is it feasible to take u-boot binary as `boot.bin`?

**Comment by DavidSpickett** [comment]
> Is it feasible to take u-boot binary as boot.bin?

Almost certainly yes, but I think in our case it's far too complicated for the problem at hand. Which is that I'm bending the use case for `-kernel` a bit too much.

I've fixed the issue in the linked commit. By using a traditional data in rom, copied to ram before/at runtime style. Tested on QEMU 5.1.0 as well so your issue should be fixed now. Let me know if not.

I'm going to move the CI to Ubuntu 20.04 at some point and that will get us a newer QEMU (4.x I think) so we'll catch this sort of issue.
